### ISSUE TITLE
Ensure the appropriate model associations

### ISSUE THREAD

**Issue by AfroDevGirl** [AfroDevGirl/congross#5]
Representatives: `has_many :bills`, `has_many :votes`, `belongs_to :committee`, `belongs_to :sub_comittee`

Votes: `has_many :representatives`, `has_many :vote_parties`, `belongs_to :bill`

Committee: `has_many :representatives`, `has_many :subcommittees`

These are just some examples

**Comment by chelsea-shorte** [comment]
I'm taking on this one!
